### ISSUE TITLE
LPIS: Tráva na orné

### ISSUE THREAD

**Issue by pschonmann** [mkyral/josm-tracer#11]
Čau, chybí tráva na orné

parseXML() - Start
parseXML(extra) - expUsage: //*[name()='ms:LPIS_FB4'][1]/*[name()='ms:kultura']
  Warning: unknown value: tráva na orné
parseXML(extra) - m_usage: tráva na orné
parseXML() - End
  LPIS ID: 12896711
  LPIS usage: tráva na orné

**Comment by mkyral** [comment]
Pěkné. To bude nějaká novinka. Nějaký návrh na správné tagování?

**Comment by pschonmann** [comment]
jentak od boku grassland ?
http://wiki.openstreetmap.org/wiki/Tag:natural%3Dgrassland

**Comment by pschonmann** [comment]
A jestli se o to nekdo stara
http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dgrass

**Comment by mkyral** [comment]
grassland - ...natural area...
grass - ...smaller areas...

Mně to přijde jako dočasně zatravněné pole. Třeba jetel na krmení. To už raději landuse=farmland a hop=grass.

Ale třeba se mýlím. Chtělo by to ověřit aktuální stav přímo v terénu.

**Comment by mkyral** [comment]
Already fixed.
