### ISSUE TITLE
RUIAN Tracer

### ISSUE THREAD

**Issue by pschonmann** [mkyral/josm-tracer#15]
Stává se, že tracer detekuje rozdil v tagu start_date. Pritom se jedna o stejne datum, jen jiny zapis. Slo by to sjednotit ? Dat treba na tenhle tag vyjimku v konfliktech a rovnou prepisovat na yyyy-mm-dd ?

![konflikt](https://cloud.githubusercontent.com/assets/6333844/7336992/492f15a6-ec17-11e4-8ef9-5c3ca6f433f5.png)

**Comment by mkyral** [comment]
Ahoj, Až bude chvilku času, ,tak na to mrknu.

**Comment by pschonmann** [comment]
Stále neprepisuje nektere hodnoty. Asi jeste nejaky bordel ve forme casu.

![notsolved](https://cloud.githubusercontent.com/assets/6333844/8315596/28d00140-19f2-11e5-8e09-355c7f773e65.jpg)

**Comment by mkyral** [comment]
S tímhle jsem se ještě nepotkal. Ta hodnota s časem je ta, která se má přepsat že? Vyskytuje se to často? Nemáš nějaký aktuální příklad?

**Comment by pschonmann** [comment]
https://www.openstreetmap.org/way/313700002/history

**Comment by mkyral** [comment]
Díky. Sice to bude asi velká výjimka, ale mělo by to být opraveno.

**Comment by pschonmann** [comment]
Myslím že to vyjímka nebude :)
Třeba tady máme okolo 200 výskytů jednoho konkrétního data http://taginfo.openstreetmap.org/tags/start_date=2000-11-14T00%3A00%3A00#overview

**Comment by mkyral** [comment]
Máš pravdu. Zdá se, že ve všech případech je autorem Pavel Kwieczien. Ten na to má nějaký vlastní nástroj mám ten dojem. Protože Tracer tam žádný zbytečný čas necpe. Zkusím mu napsat.

http://overpass-turbo.eu/s/ani
