### ISSUE TITLE
Konflikt při slučování

### ISSUE THREAD

**Issue by pschonmann** [mkyral/josm-tracer#19]
Když má building:levels=0 (což je blbost) - (zase jsem na tyhle špeky narazil u uživatele kwiecpav) a při trasování je zjištěna nenulová hodnota, tak bych ji tiše přepsal na tu smysluplnou, nenulovou.

![clipboard01](https://cloud.githubusercontent.com/assets/6333844/11826564/74f24f74-a386-11e5-9652-f900dea8f887.jpg)

**Comment by mkyral** [comment]
OK, to vypadá rozumně - až bude čas a vzpomenu si, tak na to mrknu.
