### ISSUE TITLE
porovnání konfliktů

### ISSUE THREAD

**Issue by pschonmann** [mkyral/josm-tracer#21]
Ahoj,
šlo by prosím udělat v okýnku které nám dává na výběr co máme konfliktního i nějaký nástroj podle kterého se můžeme rozhodnout ?
Ideálně něco jako historie, kde lze vidět jaké tagy byly přidávány.  Nebo aspň ukázat který tak klíč, tag je starší a který se nově snaží dotáhnout z RUIAN.

**Comment by mkyral** [comment]
Jo, to by se mi taky líbilo. Ale nevím jak na to :-(

**Comment by mkyral** [comment]
Něco mně napadlo. Fungovat by to mělo, tak se to snad povede ;-)
