### ISSUE TITLE
if Ways are equal! then tracer doesnt update key/values

### ISSUE THREAD

**Issue by pschonmann** [mkyral/josm-tracer#3]
When i want update ruianized building and nothing changed in geometry, plugin not update new values. I must delete building and click on it again to get new values with same geometry

Request: http://josm.poloha.net/tracer/tracer/?lat=50.27232884269099&lon=14.499588859153265
Reply: {"coordinates":{"lat":"50.27232884269099","lon":"14.499588859153265"},"source":"cuzk:ruian","stavebni_objekt":{"ruian_id":"51417634","cislo_dom
ovni":"756","cislo_domovni_typ":"\u010c\u00edslo popisn\u00e9","cislo_orientacni":null,"adresni_misto_kod":"41105028","ulice":"Za V\u00e1hou","cast_ob
ce":"Libi\u0161","mestska_cast":null,"obec":"Libi\u0161","okres":"M\u011bln\u00edk","kraj":"St\u0159edo\u010desk\u00fd kraj","psc":"27711","pocet_podl
azi":"1","zpusob_vyuziti_kod":"7","zpusob_vyuziti_key":"building","zpusob_vyuziti_val":"house","pocet_bytu":"1","dokonceni":"24.07.2012","plati_od":"0
4.01.2014"},"geometry":[[14.499676230491900242,50.272300818956601631],[14.499702225596900362,50.27226652484490188],[14.499573095842199777,50.272226006
421902866],[14.499545293220300834,50.272262138655001706],[14.499532519189600066,50.272258298591502523],[14.499487689817600611,50.272316533656301374],[
14.499630098999700678,50.272361843849303398],[14.499655721295100719,50.272327970827099364],[14.499648140256699236,50.272325674094098247],[14.499668668
434500418,50.272298433144001706],[14.499676230491900242,50.272300818956601631]],"adresni_mista":[]}
lat: 50.27232884269099
lat: 14.499588859153265
i=0
coor: LatLon[lat=50.2723008189566,lon=14.4996762304919]
i=1
coor: LatLon[lat=50.2722665248449,lon=14.4997022255969]
i=2
coor: LatLon[lat=50.2722260064219,lon=14.4995730958422]
i=3
coor: LatLon[lat=50.272262138655,lon=14.4995452932203]
i=4
coor: LatLon[lat=50.2722582985915,lon=14.4995325191896]
i=5
coor: LatLon[lat=50.2723165336563,lon=14.4994876898176]
i=6
coor: LatLon[lat=50.2723618438493,lon=14.4996300989997]
i=7
coor: LatLon[lat=50.2723279708271,lon=14.4996557212951]
i=8
coor: LatLon[lat=50.2723256740941,lon=14.4996481402567]
i=9
coor: LatLon[lat=50.272298433144,lon=14.4996686684345]
i=10
coor: LatLon[lat=50.2723008189566,lon=14.4996762304919]
-------
Node: {Node id=-23605 version=0 V lat=50.2723008189566,lon=14.4996762304919}
Node: {Node id=2645375019 version=1 MVD lat=50.2722984,lon=14.4996687}
Node: {Node id=2645375021 version=1 MVD lat=50.2723008,lon=14.4996762}
Node: {Node id=2645375035 version=1 MVD lat=50.2723257,lon=14.4996481}
Node: {Node id=2645375037 version=1 MVD lat=50.272328,lon=14.4996557}
Node: {Node id=2645375031 version=1 MVD lat=50.2723165,lon=14.4994877}
Node: {Node id=2645375055 version=1 MVD lat=50.2723618,lon=14.4996301}
Node: {Node id=2782089084 version=1 VT lat=50.2723001,lon=14.4995923}
Node: {Node id=2645375006 version=1 MVD lat=50.2722665,lon=14.4997022}
Node: {Node id=2645375004 version=1 MVD lat=50.2722621,lon=14.4995453}
Node: {Node id=2645375000 version=1 MVD lat=50.2722583,lon=14.4995325}
Node: {Node id=2645374990 version=1 MVD lat=50.272226,lon=14.4995731}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
-------
Node: {Node id=-23606 version=0 V lat=50.2722665248449,lon=14.4997022255969}
Node: {Node id=2645375019 version=1 MVD lat=50.2722984,lon=14.4996687}
Node: {Node id=2645375021 version=1 MVD lat=50.2723008,lon=14.4996762}
Node: {Node id=2645375035 version=1 MVD lat=50.2723257,lon=14.4996481}
Node: {Node id=2645375037 version=1 MVD lat=50.272328,lon=14.4996557}
Node: {Node id=2645375031 version=1 MVD lat=50.2723165,lon=14.4994877}
Node: {Node id=2645375055 version=1 MVD lat=50.2723618,lon=14.4996301}
Node: {Node id=2782089084 version=1 VT lat=50.2723001,lon=14.4995923}
Node: {Node id=2645375006 version=1 MVD lat=50.2722665,lon=14.4997022}
Node: {Node id=2645375004 version=1 MVD lat=50.2722621,lon=14.4995453}
Node: {Node id=2645375000 version=1 MVD lat=50.2722583,lon=14.4995325}
Node: {Node id=2645374990 version=1 MVD lat=50.272226,lon=14.4995731}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
-------
Node: {Node id=-23607 version=0 V lat=50.2722260064219,lon=14.4995730958422}
Node: {Node id=2645375019 version=1 MVD lat=50.2722984,lon=14.4996687}
Node: {Node id=2645375021 version=1 MVD lat=50.2723008,lon=14.4996762}
Node: {Node id=2645375035 version=1 MVD lat=50.2723257,lon=14.4996481}
Node: {Node id=2645375037 version=1 MVD lat=50.272328,lon=14.4996557}
Node: {Node id=2645375031 version=1 MVD lat=50.2723165,lon=14.4994877}
Node: {Node id=2645375055 version=1 MVD lat=50.2723618,lon=14.4996301}
Node: {Node id=2782089084 version=1 VT lat=50.2723001,lon=14.4995923}
Node: {Node id=2645375006 version=1 MVD lat=50.2722665,lon=14.4997022}
Node: {Node id=2645375004 version=1 MVD lat=50.2722621,lon=14.4995453}
Node: {Node id=2645375000 version=1 MVD lat=50.2722583,lon=14.4995325}
Node: {Node id=2645374990 version=1 MVD lat=50.272226,lon=14.4995731}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
-------
Node: {Node id=-23608 version=0 V lat=50.272262138655,lon=14.4995452932203}
Node: {Node id=2645375019 version=1 MVD lat=50.2722984,lon=14.4996687}
Node: {Node id=2645375021 version=1 MVD lat=50.2723008,lon=14.4996762}
Node: {Node id=2645375035 version=1 MVD lat=50.2723257,lon=14.4996481}
Node: {Node id=2645375037 version=1 MVD lat=50.272328,lon=14.4996557}
Node: {Node id=2645375031 version=1 MVD lat=50.2723165,lon=14.4994877}
Node: {Node id=2645375055 version=1 MVD lat=50.2723618,lon=14.4996301}
Node: {Node id=2782089084 version=1 VT lat=50.2723001,lon=14.4995923}
Node: {Node id=2645375006 version=1 MVD lat=50.2722665,lon=14.4997022}
Node: {Node id=2645375004 version=1 MVD lat=50.2722621,lon=14.4995453}
Node: {Node id=2645375000 version=1 MVD lat=50.2722583,lon=14.4995325}
Node: {Node id=2645374990 version=1 MVD lat=50.272226,lon=14.4995731}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
-------
Node: {Node id=-23609 version=0 V lat=50.2722582985915,lon=14.4995325191896}
Node: {Node id=2645375019 version=1 MVD lat=50.2722984,lon=14.4996687}
Node: {Node id=2645375021 version=1 MVD lat=50.2723008,lon=14.4996762}
Node: {Node id=2645375035 version=1 MVD lat=50.2723257,lon=14.4996481}
Node: {Node id=2645375037 version=1 MVD lat=50.272328,lon=14.4996557}
Node: {Node id=2645375031 version=1 MVD lat=50.2723165,lon=14.4994877}
Node: {Node id=2645375055 version=1 MVD lat=50.2723618,lon=14.4996301}
Node: {Node id=2782089084 version=1 VT lat=50.2723001,lon=14.4995923}
Node: {Node id=2645375006 version=1 MVD lat=50.2722665,lon=14.4997022}
Node: {Node id=2645375004 version=1 MVD lat=50.2722621,lon=14.4995453}
Node: {Node id=2645375000 version=1 MVD lat=50.2722583,lon=14.4995325}
Node: {Node id=2645374990 version=1 MVD lat=50.272226,lon=14.4995731}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
-------
Node: {Node id=-23610 version=0 V lat=50.2723165336563,lon=14.4994876898176}
Node: {Node id=2645375019 version=1 MVD lat=50.2722984,lon=14.4996687}
Node: {Node id=2645375021 version=1 MVD lat=50.2723008,lon=14.4996762}
Node: {Node id=2645375035 version=1 MVD lat=50.2723257,lon=14.4996481}
Node: {Node id=2645375037 version=1 MVD lat=50.272328,lon=14.4996557}
Node: {Node id=2645375031 version=1 MVD lat=50.2723165,lon=14.4994877}
Node: {Node id=2645375055 version=1 MVD lat=50.2723618,lon=14.4996301}
Node: {Node id=2782089084 version=1 VT lat=50.2723001,lon=14.4995923}
Node: {Node id=2645375006 version=1 MVD lat=50.2722665,lon=14.4997022}
Node: {Node id=2645375004 version=1 MVD lat=50.2722621,lon=14.4995453}
Node: {Node id=2645375000 version=1 MVD lat=50.2722583,lon=14.4995325}
Node: {Node id=2645374990 version=1 MVD lat=50.272226,lon=14.4995731}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
-------
Node: {Node id=-23611 version=0 V lat=50.2723618438493,lon=14.4996300989997}
Node: {Node id=2645375019 version=1 MVD lat=50.2722984,lon=14.4996687}
Node: {Node id=2645375021 version=1 MVD lat=50.2723008,lon=14.4996762}
Node: {Node id=2645375035 version=1 MVD lat=50.2723257,lon=14.4996481}
Node: {Node id=2645375037 version=1 MVD lat=50.272328,lon=14.4996557}
Node: {Node id=2645375031 version=1 MVD lat=50.2723165,lon=14.4994877}
Node: {Node id=2645375055 version=1 MVD lat=50.2723618,lon=14.4996301}
Node: {Node id=2782089084 version=1 VT lat=50.2723001,lon=14.4995923}
Node: {Node id=2645375006 version=1 MVD lat=50.2722665,lon=14.4997022}
Node: {Node id=2645375004 version=1 MVD lat=50.2722621,lon=14.4995453}
Node: {Node id=2645375000 version=1 MVD lat=50.2722583,lon=14.4995325}
Node: {Node id=2645374990 version=1 MVD lat=50.272226,lon=14.4995731}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
-------
Node: {Node id=-23612 version=0 V lat=50.2723279708271,lon=14.4996557212951}
Node: {Node id=2645375019 version=1 MVD lat=50.2722984,lon=14.4996687}
Node: {Node id=2645375021 version=1 MVD lat=50.2723008,lon=14.4996762}
Node: {Node id=2645375035 version=1 MVD lat=50.2723257,lon=14.4996481}
Node: {Node id=2645375037 version=1 MVD lat=50.272328,lon=14.4996557}
Node: {Node id=2645375031 version=1 MVD lat=50.2723165,lon=14.4994877}
Node: {Node id=2645375055 version=1 MVD lat=50.2723618,lon=14.4996301}
Node: {Node id=2782089084 version=1 VT lat=50.2723001,lon=14.4995923}
Node: {Node id=2645375006 version=1 MVD lat=50.2722665,lon=14.4997022}
Node: {Node id=2645375004 version=1 MVD lat=50.2722621,lon=14.4995453}
Node: {Node id=2645375000 version=1 MVD lat=50.2722583,lon=14.4995325}
Node: {Node id=2645374990 version=1 MVD lat=50.272226,lon=14.4995731}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
-------
Node: {Node id=-23613 version=0 V lat=50.2723256740941,lon=14.4996481402567}
Node: {Node id=2645375019 version=1 MVD lat=50.2722984,lon=14.4996687}
Node: {Node id=2645375021 version=1 MVD lat=50.2723008,lon=14.4996762}
Node: {Node id=2645375035 version=1 MVD lat=50.2723257,lon=14.4996481}
Node: {Node id=2645375037 version=1 MVD lat=50.272328,lon=14.4996557}
Node: {Node id=2645375031 version=1 MVD lat=50.2723165,lon=14.4994877}
Node: {Node id=2645375055 version=1 MVD lat=50.2723618,lon=14.4996301}
Node: {Node id=2782089084 version=1 VT lat=50.2723001,lon=14.4995923}
Node: {Node id=2645375006 version=1 MVD lat=50.2722665,lon=14.4997022}
Node: {Node id=2645375004 version=1 MVD lat=50.2722621,lon=14.4995453}
Node: {Node id=2645375000 version=1 MVD lat=50.2722583,lon=14.4995325}
Node: {Node id=2645374990 version=1 MVD lat=50.272226,lon=14.4995731}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
-------
Node: {Node id=-23614 version=0 V lat=50.272298433144,lon=14.4996686684345}
Node: {Node id=2645375019 version=1 MVD lat=50.2722984,lon=14.4996687}
Node: {Node id=2645375021 version=1 MVD lat=50.2723008,lon=14.4996762}
Node: {Node id=2645375035 version=1 MVD lat=50.2723257,lon=14.4996481}
Node: {Node id=2645375037 version=1 MVD lat=50.272328,lon=14.4996557}
Node: {Node id=2645375031 version=1 MVD lat=50.2723165,lon=14.4994877}
Node: {Node id=2645375055 version=1 MVD lat=50.2723618,lon=14.4996301}
Node: {Node id=2782089084 version=1 VT lat=50.2723001,lon=14.4995923}
Node: {Node id=2645375006 version=1 MVD lat=50.2722665,lon=14.4997022}
Node: {Node id=2645375004 version=1 MVD lat=50.2722621,lon=14.4995453}
Node: {Node id=2645375000 version=1 MVD lat=50.2722583,lon=14.4995325}
Node: {Node id=2645374990 version=1 MVD lat=50.272226,lon=14.4995731}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
{Node id=-23605 version=0 V lat=50.2723008189566,lon=14.4996762304919}-----{Node id=-23606 version=0 V lat=50.2722665248449,lon=14.4997022255969}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23606 version=0 V lat=50.2722665248449,lon=14.4997022255969}-----{Node id=-23607 version=0 V lat=50.2722260064219,lon=14.4995730958422}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23607 version=0 V lat=50.2722260064219,lon=14.4995730958422}-----{Node id=-23608 version=0 V lat=50.272262138655,lon=14.4995452932203}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23608 version=0 V lat=50.272262138655,lon=14.4995452932203}-----{Node id=-23609 version=0 V lat=50.2722582985915,lon=14.4995325191896}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23609 version=0 V lat=50.2722582985915,lon=14.4995325191896}-----{Node id=-23610 version=0 V lat=50.2723165336563,lon=14.4994876898176}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23610 version=0 V lat=50.2723165336563,lon=14.4994876898176}-----{Node id=-23611 version=0 V lat=50.2723618438493,lon=14.4996300989997}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23611 version=0 V lat=50.2723618438493,lon=14.4996300989997}-----{Node id=-23612 version=0 V lat=50.2723279708271,lon=14.4996557212951}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23612 version=0 V lat=50.2723279708271,lon=14.4996557212951}-----{Node id=-23613 version=0 V lat=50.2723256740941,lon=14.4996481402567}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23613 version=0 V lat=50.2723256740941,lon=14.4996481402567}-----{Node id=-23614 version=0 V lat=50.272298433144,lon=14.4996686684345}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23614 version=0 V lat=50.272298433144,lon=14.4996686684345}-----{Node id=-23605 version=0 V lat=50.2723008189566,lon=14.4996762304919}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23605 version=0 V lat=50.2723008189566,lon=14.4996762304919}-----{Node id=-23605 version=0 V lat=50.2723008189566,lon=14.4996762304919}
Nearest_: null distance: 1.7976931348623157E308

Commands: [org.openstreetmap.josm.command.AddCommand@57e996b6, org.openstreetmap.josm.command.AddCommand@28a5b3d1, org.openstreetmap.josm.command.AddC
ommand@16c07330, org.openstreetmap.josm.command.AddCommand@34ca5ffb, org.openstreetmap.josm.command.AddCommand@526372d0, org.openstreetmap.josm.comman
d.AddCommand@7f06dff1, org.openstreetmap.josm.command.AddCommand@1c58885e, org.openstreetmap.josm.command.AddCommand@7860e1db, org.openstreetmap.josm.
command.AddCommand@208c2e9b, org.openstreetmap.josm.command.AddCommand@5347d2ce, org.openstreetmap.josm.command.SequenceCommand@1060fd19]
Request: http://josm.poloha.net/tracer/tracer/?lat=50.27219743366926&lon=14.49926137204563
Reply: {"coordinates":{"lat":"50.27219743366926","lon":"14.49926137204563"},"source":"cuzk:ruian","stavebni_objekt":{"ruian_id":"27852881","cislo_domo
vni":"741","cislo_domovni_typ":"\u010c\u00edslo popisn\u00e9","cislo_orientacni":null,"adresni_misto_kod":"28394640","ulice":"Za V\u00e1hou","cast_obc
e":"Libi\u0161","mestska_cast":null,"obec":"Libi\u0161","okres":"M\u011bln\u00edk","kraj":"St\u0159edo\u010desk\u00fd kraj","psc":"27711","pocet_podla
zi":null,"zpusob_vyuziti_kod":"7","zpusob_vyuziti_key":"building","zpusob_vyuziti_val":"house","pocet_bytu":null,"dokonceni":"26.04.2011","plati_od":"
27.01.2014"},"geometry":[[14.499194230780799941,50.272243214108499387],[14.4993074463311995,50.272279345867502798],[14.499382397951199763,50.272182731
621199991],[14.49926878457219992,50.272146474363097468],[14.499194230780799941,50.272243214108499387]],"adresni_mista":[]}
lat: 50.27219743366926
lat: 14.49926137204563
i=0
coor: LatLon[lat=50.2722432141085,lon=14.4991942307808]
i=1
coor: LatLon[lat=50.2722793458675,lon=14.4993074463312]
i=2
coor: LatLon[lat=50.2721827316212,lon=14.4993823979512]
i=3
coor: LatLon[lat=50.2721464743631,lon=14.4992687845722]
i=4
coor: LatLon[lat=50.2722432141085,lon=14.4991942307808]
Old and New was have 5 nodes
New.Node(0) = lat=50,27224░, lon=14,49919░
 -> Old.Node(0) = lat=50,27224░, lon=14,49919░
Nodes: New(0) and Old(0) are equal.
New.Node(1) = lat=50,27228░, lon=14,49931░
 -> Old.Node(0) = lat=50,27224░, lon=14,49919░
 -> Old.Node(1) = lat=50,27228░, lon=14,49931░
Nodes: New(1) and Old(1) are equal.
New.Node(2) = lat=50,27218░, lon=14,49938░
 -> Old.Node(0) = lat=50,27224░, lon=14,49919░
 -> Old.Node(1) = lat=50,27228░, lon=14,49931░
 -> Old.Node(2) = lat=50,27218░, lon=14,49938░
Nodes: New(2) and Old(2) are equal.
New.Node(3) = lat=50,27215░, lon=14,49927░
 -> Old.Node(0) = lat=50,27224░, lon=14,49919░
 -> Old.Node(1) = lat=50,27228░, lon=14,49931░
 -> Old.Node(2) = lat=50,27218░, lon=14,49938░
 -> Old.Node(3) = lat=50,27215░, lon=14,49927░
Nodes: New(3) and Old(3) are equal.
New.Node(4) = lat=50,27224░, lon=14,49919░
 -> Old.Node(0) = lat=50,27224░, lon=14,49919░
Nodes: New(4) and Old(0) are equal.
nodesCount = 5; nodesFound = 5
Ways are equal!
Request: http://josm.poloha.net/tracer/tracer/?lat=50.2722068762458&lon=14.49930692476361
Reply: {"coordinates":{"lat":"50.2722068762458","lon":"14.49930692476361"},"source":"cuzk:ruian","stavebni_objekt":{"ruian_id":"27852881","cislo_domov
ni":"741","cislo_domovni_typ":"\u010c\u00edslo popisn\u00e9","cislo_orientacni":null,"adresni_misto_kod":"28394640","ulice":"Za V\u00e1hou","cast_obce
":"Libi\u0161","mestska_cast":null,"obec":"Libi\u0161","okres":"M\u011bln\u00edk","kraj":"St\u0159edo\u010desk\u00fd kraj","psc":"27711","pocet_podlaz
i":null,"zpusob_vyuziti_kod":"7","zpusob_vyuziti_key":"building","zpusob_vyuziti_val":"house","pocet_bytu":null,"dokonceni":"26.04.2011","plati_od":"2
7.01.2014"},"geometry":[[14.499194230780799941,50.272243214108499387],[14.4993074463311995,50.272279345867502798],[14.499382397951199763,50.2721827316
21199991],[14.49926878457219992,50.272146474363097468],[14.499194230780799941,50.272243214108499387]],"adresni_mista":[]}
lat: 50.2722068762458
lat: 14.49930692476361
i=0
coor: LatLon[lat=50.2722432141085,lon=14.4991942307808]
i=1
coor: LatLon[lat=50.2722793458675,lon=14.4993074463312]
i=2
coor: LatLon[lat=50.2721827316212,lon=14.4993823979512]
i=3
coor: LatLon[lat=50.2721464743631,lon=14.4992687845722]
i=4
coor: LatLon[lat=50.2722432141085,lon=14.4991942307808]
-------
Node: {Node id=-23627 version=0 V lat=50.2722432141085,lon=14.4991942307808}
Node: {Node id=2645374996 version=1 MVD lat=50.2722432,lon=14.4991942}
Node: {Node id=2645375014 version=1 MVD lat=50.2722793,lon=14.4993074}
Node: {Node id=2782089039 version=1 VT lat=50.2722212,lon=14.4992866}
Node: {Node id=2645374963 version=1 MVD lat=50.2721465,lon=14.4992688}
Node: {Node id=2645374977 version=1 MVD lat=50.2721827,lon=14.4993824}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
-------
Node: {Node id=-23628 version=0 V lat=50.2722793458675,lon=14.4993074463312}
Node: {Node id=2645374996 version=1 MVD lat=50.2722432,lon=14.4991942}
Node: {Node id=2645375014 version=1 MVD lat=50.2722793,lon=14.4993074}
Node: {Node id=2782089039 version=1 VT lat=50.2722212,lon=14.4992866}
Node: {Node id=2645374963 version=1 MVD lat=50.2721465,lon=14.4992688}
Node: {Node id=2645374977 version=1 MVD lat=50.2721827,lon=14.4993824}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
-------
Node: {Node id=-23629 version=0 V lat=50.2721827316212,lon=14.4993823979512}
Node: {Node id=2645374996 version=1 MVD lat=50.2722432,lon=14.4991942}
Node: {Node id=2645375014 version=1 MVD lat=50.2722793,lon=14.4993074}
Node: {Node id=2782089039 version=1 VT lat=50.2722212,lon=14.4992866}
Node: {Node id=2645374963 version=1 MVD lat=50.2721465,lon=14.4992688}
Node: {Node id=2645374977 version=1 MVD lat=50.2721827,lon=14.4993824}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
-------
Node: {Node id=-23630 version=0 V lat=50.2721464743631,lon=14.4992687845722}
Node: {Node id=2645374996 version=1 MVD lat=50.2722432,lon=14.4991942}
Node: {Node id=2645375014 version=1 MVD lat=50.2722793,lon=14.4993074}
Node: {Node id=2782089039 version=1 VT lat=50.2722212,lon=14.4992866}
Node: {Node id=2645374963 version=1 MVD lat=50.2721465,lon=14.4992688}
Node: {Node id=2645374977 version=1 MVD lat=50.2721827,lon=14.4993824}
Nearest: null distance: 5.0E-7
Nearest way: null distance: 1.7976931348623157E308
{Node id=-23627 version=0 V lat=50.2722432141085,lon=14.4991942307808}-----{Node id=-23628 version=0 V lat=50.2722793458675,lon=14.4993074463312}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23628 version=0 V lat=50.2722793458675,lon=14.4993074463312}-----{Node id=-23629 version=0 V lat=50.2721827316212,lon=14.4993823979512}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23629 version=0 V lat=50.2721827316212,lon=14.4993823979512}-----{Node id=-23630 version=0 V lat=50.2721464743631,lon=14.4992687845722}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23630 version=0 V lat=50.2721464743631,lon=14.4992687845722}-----{Node id=-23627 version=0 V lat=50.2722432141085,lon=14.4991942307808}
Nearest_: null distance: 1.7976931348623157E308

{Node id=-23627 version=0 V lat=50.2722432141085,lon=14.4991942307808}-----{Node id=-23627 version=0 V lat=50.2722432141085,lon=14.4991942307808}
Nearest_: null distance: 1.7976931348623157E308

Commands: [org.openstreetmap.josm.command.AddCommand@24d03b5e, org.openstreetmap.josm.command.AddCommand@62e9ab33, org.openstreetmap.josm.command.AddC
ommand@5ae6d400, org.openstreetmap.josm.command.AddCommand@68687a9f, org.openstreetmap.josm.command.SequenceCommand@234a9246]

**Comment by mkyral** [comment]
Already fixed.
