### ISSUE TITLE
Tiche prepsani hodnoty building=residential

### ISSUE THREAD

**Issue by pschonmann** [mkyral/josm-tracer#33]
http://wiki.openstreetmap.org/wiki/Tag:building%3Dresidential

building=residential bych prepisoval tise  či ignoroval kdyz je specifikovano podrobneji při retrasování. Typicky
![clipboard01](https://cloud.githubusercontent.com/assets/6333844/20160311/484db38c-a6e6-11e6-877f-dbaccf6f0786.png)

**Comment by mkyral** [comment]
Jé,
tady je nové issue. A už tak dlouho. Jsem nějak přehlídl :-(

**Comment by mkyral** [comment]
Opraveno a publikováno.

**Comment by pschonmann** [comment]
Nejsem si jist zda oprava funguje. Například zde https://www.openstreetmap.org/way/288237854 je natrasovano house, residential v OSM, nicmene rozdilne je i building:ruian:type ktere asi brani tichemu prepsani.
