### ISSUE TITLE
java.lang.NoSuchMethodError: org.openstreetmap.josm.gui.conflict.tags.CombinePrimitiveResolverDialog.getInstance()

### ISSUE THREAD

**Issue by mkyral** [mkyral/josm-tracer#38]
```
java.lang.NoSuchMethodError: org.openstreetmap.josm.gui.conflict.tags.CombinePrimitiveResolverDialog.getInstance()Lorg/openstreetmap/josm/gui/conflict/tags/CombinePrimitiveResolverDialog;
	at org.openstreetmap.josm.plugins.tracer.CombineTagsResolver.launchIfNecessary(CombineTagsResolver.java:93)
	at org.openstreetmap.josm.plugins.tracer.modules.lpis.LpisModule$LpisTracerTask.tagTracedObject(LpisModule.java:369)
	at org.openstreetmap.josm.plugins.tracer.modules.lpis.LpisModule$LpisTracerTask.createTracedPolygonImpl(LpisModule.java:275)
	at org.openstreetmap.josm.plugins.tracer.TracerModule$AbstractTracerTask$6.run(TracerModule.java:348)
```

Ke změně došlo v commitu: https://github.com/openstreetmap/josm/commit/70baab40d3c2ba86bf1546126d267e8f1c0a0081

Funkce CombinePrimitiveResolverDialog.getInstance() byla odstraněna.

Komentář v kódu Traceru:

_// Note 1: this method was copied from CombinePrimitiveResolverDialog.launchIfNecessary() and
// adapted to resolution of tag sets only. It's not possible to use the original launchIfNecessary()
// because (a) it requires primitives occurring in DataSet, (b) it tries to resolve relation
// memberships, (c) it builds a list of DataSet Commands instead of the resolved set of tags._

_// Note 2: this method relies on deprecated function CombinePrimitiveResolverDialog.getInstance().
// The function was deprecated by introduction of CombinePrimitiveResolverDialog.launchIfNecessary()
// but it's still available for public use._

**Comment by Maatts** [comment]
Poslal jsem pull request, který řeší popsaný problém plus pár dalších deprecated funkcí a problémů, viz changelog. Po dvou letech nečinnosti jsem dost vařil z vody, takže prosím vyzkoušet před finálním releasem :-)

**Comment by mkyral** [comment]
Jasně. Otestuji a pustím. Ale asi až zítra. Díky moc.
