### ISSUE TITLE
Update tracer to JOSM 13807

### ISSUE THREAD

**Issue by don-vip** [mkyral/josm-tracer#43]
Hello,
I've made some changes to `Geometry` class:
* [13805](https://josm.openstreetmap.de/changeset/13805/josm/trunk/src/org/openstreetmap/josm/tools/Geometry.java)
* [13807](https://josm.openstreetmap.de/changeset/13807/josm/trunk/src/org/openstreetmap/josm/tools/Geometry.java)

The plugin needs to be recompiled against latest JOSM and Main-Version increased, see [Plugin incompatibilities](https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/warnings3)

```
WayEditor:559,           Tracer-testing, Priority: Normale
--
boolean  org.openstreetmap.josm.tools.Geometry.isNodeInsideMultiPolygon(org.openstreetmap.josm.data.osm.Node,  org.openstreetmap.josm.data.osm.Relation, java.util.function.Predicate)

WayEditor:570,           Tracer-testing, Priority: Normale
--
boolean org.openstreetmap.josm.tools.Geometry.nodeInsidePolygon(org.openstreetmap.josm.data.osm.Node, java.util.List)
```

**Comment by mkyral** [comment]
Hi @don-vip Thanks a lot for the info.
