### ISSUE TITLE
download site with invalid ssl certificate

### ISSUE THREAD

**Issue by Klumbumbus** [mkyral/josm-tracer#50]
On https://josm.openstreetmap.de/wiki/PluginsSource the download link for this plugin is listed as https://osm.kyralovi.cz/bin/Tracer-testing.jar. However this page has an invalid ssl certificate. Could you please fix this page or change the download link pointing to a valid page?

Warning in JOSM:
![grafik](https://user-images.githubusercontent.com/7115609/94197015-76917000-feb5-11ea-8eb9-9e7c033132ad.png)

Warning in firefox:
![grafik](https://user-images.githubusercontent.com/7115609/94196962-61b4dc80-feb5-11ea-8890-5e9f7243d7b2.png)

**Comment by mkyral** [comment]
Hi,
unfortunately, my hosting provider was hacked and hackers deleted all hosting configuration. They still working on it, but It seems that correct certificate is back now.
